# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: angular-viewer-sample-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  angular-viewer-sample-CI:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

        # Configures git to use imodeljs-admin user
      - name: Checkout branch
        run: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin

      # use Node 16
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |
          npm --version

      - name: Install Deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:ci
